063-gtp-common-conf: get features corresponding to IBUFDS -> GTP
SymbiFlow/prjxray pull request #1566
Opened 2021-01-28 19:25 UTC by acomodi

Signed-off-by: Alessandro Comodi <acomodi@antmicro.com>

This changes allow to document features that appearr when the GTREFCLK ports of the GTP_COMMON are connected to the IBUFDS_GTE2 sites' outputs.

2021-01-29 16:14 UTC, litghost commented
I believe something is broken, because the GTP COMMON features just moved their frame offsets:
```
-GTP_CHANNEL_0_MID_LEFT.GTPE2.ACJTAG_DEBUG_MODE[0] 00_07
-GTP_CHANNEL_0_MID_LEFT.GTPE2.ACJTAG_MODE[0] 01_06
-GTP_CHANNEL_0_MID_LEFT.GTPE2.ACJTAG_RESET[0] 01_07
-GTP_CHANNEL_0_MID_LEFT.GTPE2.ADAPT_CFG0[0] 02_464
-GTP_CHANNEL_0_MID_LEFT.GTPE2.ADAPT_CFG0[1] 03_464
-GTP_CHANNEL_0_MID_LEFT.GTPE2.ADAPT_CFG0[2] 02_465
-GTP_CHANNEL_0_MID_LEFT.GTPE2.ADAPT_CFG0[3] 03_465
+GTP_CHANNEL_0_MID_LEFT.GTPE2.ACJTAG_DEBUG_MODE[0] 28_07
+GTP_CHANNEL_0_MID_LEFT.GTPE2.ACJTAG_MODE[0] 29_06
+GTP_CHANNEL_0_MID_LEFT.GTPE2.ACJTAG_RESET[0] 29_07
+GTP_CHANNEL_0_MID_LEFT.GTPE2.ADAPT_CFG0[0] 30_464
+GTP_CHANNEL_0_MID_LEFT.GTPE2.ADAPT_CFG0[1] 31_464
+GTP_CHANNEL_0_MID_LEFT.GTPE2.ADAPT_CFG0[2] 30_465
+GTP_CHANNEL_0_MID_LEFT.GTPE2.ADAPT_CFG0[3] 31_465
```

2021-01-29 16:15 UTC, litghost requested changes
Seeing weird results from CI?

2021-01-29 16:24 UTC, acomodi commented
@litghost Hmm, yes, this is quite strange indeed, as the GTP_COMMON_MID and GTP_CHANNEL_MID features happen to be at frames 0 and 1. I'll check what is happening.

It is possible that there is some sort of interference between two parallel runs of the GTP_CHANNEL fuzzer, as it runs for each part simultaneously, therefore, there might be sth wrong with the pushdb step in the 064 fuzzer

2021-01-29 16:54 UTC, acomodi commented
@litghost There was indeed an issue in the pushdb script, and results for the 50/100T got pushed for the 200T as well. Fixed in https://github.com/SymbiFlow/prjxray/pull/1566/commits/a19a81d2eeca8555e965e2bf426e14adb8e0dae6

2021-02-01 15:14 UTC, litghost commented
@acomodi Results look better, but I think we have a naming issue:
```
diff --git a/artix7/segbits_gtp_common.db b/artix7/segbits_gtp_common.db
index 57d5499..0db9701 100644
--- a/artix7/segbits_gtp_common.db
+++ b/artix7/segbits_gtp_common.db
@@ -70,6 +70,7 @@ GTP_COMMON.GTPE2.BIAS_CFG[60] 28_1670
 GTP_COMMON.GTPE2.BIAS_CFG[61] 29_1670
 GTP_COMMON.GTPE2.BIAS_CFG[62] 28_1671
 GTP_COMMON.GTPE2.BIAS_CFG[63] 29_1671
+GTP_COMMON.GTPE2.BOTH_GTREFCLK_USED 29_1439 29_1807
 GTP_COMMON.GTPE2.COMMON_CFG[0] 28_1544
 GTP_COMMON.GTPE2.COMMON_CFG[1] 29_1544
 GTP_COMMON.GTPE2.COMMON_CFG[2] 28_1545
@@ -103,8 +104,6 @@ GTP_COMMON.GTPE2.COMMON_CFG[29] 29_1558
 GTP_COMMON.GTPE2.COMMON_CFG[30] 28_1559
 GTP_COMMON.GTPE2.COMMON_CFG[31] 29_1559
 GTP_COMMON.GTPE2.IN_USE 28_1584
-GTP_COMMON.GTPE2.INV_GTGREFCLK0 29_1516
-GTP_COMMON.GTPE2.INV_GTGREFCLK1 28_1514
 GTP_COMMON.GTPE2.PLL_CLKOUT_CFG[0] 28_1560
 GTP_COMMON.GTPE2.PLL_CLKOUT_CFG[1] 29_1560
 GTP_COMMON.GTPE2.PLL_CLKOUT_CFG[2] 28_1561
@@ -148,6 +147,8 @@ GTP_COMMON.GTPE2.RSVD_ATTR1[15] 29_1735
 GTP_COMMON.GTPE2.ZINV_DRPCLK 28_1516
 GTP_COMMON.GTPE2.ZINV_PLL0LOCKDETCLK 29_1512
 GTP_COMMON.GTPE2.ZINV_PLL1LOCKDETCLK 28_1512
+GTP_COMMON.GTPE2.GTREFCLK0 28_1438 28_1806
+GTP_COMMON.GTPE2.GTREFCLK1 29_1438 29_1806
 GTP_COMMON.GTPE2.PLL0_CFG[0] 28_1424
 GTP_COMMON.GTPE2.PLL0_CFG[1] 29_1424
 GTP_COMMON.GTPE2.PLL0_CFG[2] 28_1425
```

Should `GTP_COMMON.GTPE2.GTREFCLK0` be `GTP_COMMON.GTPE2.GTREFCLK0_USED` or what?  Maybe `GTP_COMMON.GTPE2.ZINV_GTREFCLK0`?

2021-02-01 15:30 UTC, acomodi commented
@litghost  This is something we could discuss a bit on as the situation is the following:

There exist wires and PIPs that allow the connections of the GTREFCLK ports to clocks coming from the device fabric instead of the IBUFDS_GTE2 primitive. In fact, if the clock comes from the device fabric, the physical `GTGREFCLK[01]` port is used instead of the `GTREFCLK[01]` one (even though the design's primitive port is always `GTREFCLK`).

In the [User Guide pg 27](https://www.xilinx.com/support/documentation/user_guides/ug482_7Series_GTP_Transceivers.pdf), it is stated that the `GTGREFCLK[01]` port is used for "internal testing purposes", and I have seen in some threads that it is highly discouraged to get the reference clock from the fabric, instead of using the external one.

That said, I believe that a possible correct naming could be `GTREFCLK[01]_USED`.

2021-02-01 15:32 UTC, litghost commented
> @litghost This is something we could discuss a bit on as the situation is the following:
> 
> There exist wires and PIPs that allow the connections of the GTREFCLK ports to clocks coming from the device fabric instead of the IBUFDS_GTE2 primitive. In fact, if the clock comes from the device fabric, the physical `GTGREFCLK[01]` port is used instead of the `GTREFCLK[01]` one (even though the design's primitive port is always `GTREFCLK`).
> 
> In the [User Guide pg 27](https://www.xilinx.com/support/documentation/user_guides/ug482_7Series_GTP_Transceivers.pdf), it is stated that the `GTGREFCLK[01]` port is used for "internal testing purposes", and I have seen in some threads that it is highly discouraged to get the reference clock from the fabric, instead of using the external one.
> 
> That said, I believe that a possible correct naming could be `GTREFCLK[01]_USED`.

Add this to the README for this fuzzer with whatever you decide.

2021-02-01 15:54 UTC, acomodi commented
> Add this to the README for this fuzzer with whatever you decide.

@litghost  Done

2021-02-04 11:34 UTC, merged