Docu fixup and prevent AssertionError
SymbiFlow/prjxray pull request #1627
Opened 2021-03-18 21:17 UTC by dnltz

2021-03-18 21:20 UTC, litghost commented on docs/db_dev_process/newpart.rst
> +uses. Because same devices share the same fabric, this mapping needs to be
`some devices`, not `same devices`

2021-03-18 21:21 UTC, litghost approved these changes
LGTM, we'll see if the CI is green.  Any idea why the CI passed without the `SKIP_ENV` change?

2021-03-18 21:53 UTC, dnltz commented
I think it's because the setting scripts does not handle the return code of the callee.
https://github.com/SymbiFlow/prjxray/blob/086f9a1714e96323947d7c2526f5e4b97063e79f/settings/artix7.sh#L36

On the other hand, the fuzzer will fail if the file does not exists.
```
make[1]: *** [Makefile:153: 073-get_counts/run.xc7a100tfgg676-1.ok] Error 1
Traceback (most recent call last):
  File ".//run_fuzzer.py", line 692, in <module>
    sys.exit(main(sys.argv))
  File ".//run_fuzzer.py", line 452, in main
    environment = get_environment_variables()
  File "/home/daniel/work/symbiflow/prjxray/utils/create_environment.py", line 39, in get_environment_variables
    resources = get_part_resources(res_path, os.environ['XRAY_PART'])
  File "/home/daniel/work/symbiflow/prjxray/prjxray/util.py", line 63, in get_part_resources
    "Mapping file {} does not exists".format(filename)
AssertionError: Mapping file /home/daniel/work/symbiflow/prjxray/settings/artix7/resources.yaml does not exists
Traceback (most recent call last):
  File ".//run_fuzzer.py", line 692, in <module>
Traceback (most recent call last):
  File ".//run_fuzzer.py", line 692, in <module>
    sys.exit(main(sys.argv))
  File ".//run_fuzzer.py", line 452, in main
    sys.exit(main(sys.argv))
    environment = get_environment_variables()
  File "/home/daniel/work/symbiflow/prjxray/utils/create_environment.py", line 39, in get_environment_variables
  File ".//run_fuzzer.py", line 452, in main
    resources = get_part_resources(res_path, os.environ['XRAY_PART'])
  File "/home/daniel/work/symbiflow/prjxray/prjxray/util.py", line 63, in get_part_resources
    "Mapping file {} does not exists".format(filename)
AssertionError: Mapping file /home/daniel/work/symbiflow/prjxray/settings/artix7/resources.yaml does not exists
    environment = get_environment_variables()
  File "/home/daniel/work/symbiflow/prjxray/utils/create_environment.py", line 39, in get_environment_variables
    resources = get_part_resources(res_path, os.environ['XRAY_PART'])
  File "/home/daniel/work/symbiflow/prjxray/prjxray/util.py", line 63, in get_part_resources
    "Mapping file {} does not exists".format(filename)
AssertionError: Mapping file /home/daniel/work/symbiflow/prjxray/settings/artix7/resources.yaml does not exists
Traceback (most recent call last):
  File ".//run_fuzzer.py", line 692, in <module>
    sys.exit(main(sys.argv))
  File ".//run_fuzzer.py", line 452, in main
    environment = get_environment_variables()
  File "/home/daniel/work/symbiflow/prjxray/utils/create_environment.py", line 39, in get_environment_variables
    resources = get_part_resources(res_path, os.environ['XRAY_PART'])
  File "/home/daniel/work/symbiflow/prjxray/prjxray/util.py", line 63, in get_part_resources
    "Mapping file {} does not exists".format(filename)
AssertionError: Mapping file /home/daniel/work/symbiflow/prjxray/settings/artix7/resources.yaml does not exists
make[1]: *** [Makefile:87: 000-init-db/run.xc7a50tfgg484-1.ok] Error 1
make[1]: *** [Makefile:87: 000-init-db/run.xc7a100tfgg676-1.ok] Error 1
make[1]: Leaving directory '/home/daniel/work/symbiflow/prjxray/fuzzers'
make[1]: *** [Makefile:155: 075-pins/run.xc7a50tfgg484-1.ok] Error 1
make[1]: Leaving directory '/home/daniel/work/symbiflow/prjxray/fuzzers'
make: *** [Makefile:181: db-artix7] Error 2
make: *** Waiting for unfinished jobs....
make: *** [Makefile:204: db-part-only-artix7_50t] Error 2
make[1]: *** [Makefile:152: 072-ordered_wires/run.xc7a200tffg1156-1.ok] Error 1
make[1]: Leaving directory '/home/daniel/work/symbiflow/prjxray/fuzzers'
make: *** [Makefile:204: db-part-only-artix7_200t] Error 2

```

2021-03-23 12:55 UTC, dnltz commented on settings/artix7.sh
> +eval $env
@litghost - I have added this check to handle the return code correctly. What do you think?

2021-03-26 00:59 UTC, litghost requested changes
Can you rebase this PR and see if it is green now?

2021-03-30 11:15 UTC, dnltz commented
@litghost - Rebased and looks good. What do you think?

Maybe we should collect in an issue common failures. The znyq hclk and this kintex seems a little bit unstable righti now.

2021-03-30 16:44 UTC, litghost commented
> Maybe we should collect in an issue common failures. The znyq hclk and this kintex seems a little bit unstable righti now.

I agree.  These types of issues arise periodically and get squashed when people drill down and fix them.  If you want to take a look, we always appreciate the help!

2021-04-01 16:23 UTC, merged

2021-04-01 16:48 UTC, mithro commented on docs/db_dev_process/newpart.rst
> +done manuelly. Edit the device.yaml file for the used family under
`manuelly` --> `manually`

2021-04-01 16:48 UTC, mithro commented on settings/artix7_200t.sh
> +env=`python3 ${XRAY_UTILS_DIR}/create_environment.py`
Don't use backticks.